spring:
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

http:
  port: 8085 # http服务端口

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # 验证码超期时间
rabbitmq:
  host: localhost
  port: 5672
  virtual-host: /mall
  username: guest
  password: guest
  publisher-confirms: true #如果对异步消息需要回调必须设置为true
                                      # 消息队列定义

